version: '3.8'
services:
  shorten-url-service:
    image: tugayesilyurt/shorten-url-service
    container_name: shorten-url-service
    build: 
       context: ./shorten-url-service
       dockerfile: Dockerfile
    restart: on-failure
    environment:
      JAEGER_HOST: jaeger
    links:
      - jaeger
    ports:
      - "5000:5000"    
  jaeger: 
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "9411:9411"
  grafana:
    container_name: grafana
    ports:
        - "3000:3000"
    volumes:
        - /var/lib/grafana
    links:
    - prometheus
    image: grafana/grafana
  prometheus:
    container_name: prometheus
    ports:
        - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus