server:
   port: 5000
   
opentracing:
  jaeger:
    http-sender:
      url: http://${JAEGER_HOST}:14268/api/traces
spring:
  application:
    name: shorten-url-service

logging:
  level:
    io.opentracing: DEBUG
   
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true